# Generated by Django 3.1 on 2020-08-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
